### ISSUE TITLE
Periodictable website seems out-of-service

### ISSUE THREAD

**Issue by b-dantas** [tamalchowdhury/periodic-table#40]
## Expected Behavior
Loads [PeriodicTable.website](https://periodictable.website/).

## Actual Behavior
Time-out error.

## Steps to Reproduce the Problem

1. Try to access https://periodictable.website from a web browser.

## My analysis

So, I noticed that URL (https://periodictable.website/) resolves for an AWS IP and port scanning it was shows it up and running, but just a port 80 opened. Probably some service on AWS is shutdown.

![image](https://user-images.githubusercontent.com/25280984/205505268-29441d75-1927-4da6-963b-53c4741810d9.png)

![image](https://user-images.githubusercontent.com/25280984/205505452-a31fc719-ed4c-41a7-ab79-487a601d0ba2.png)

![image](https://user-images.githubusercontent.com/25280984/205505861-d7227337-e2c3-4271-9e32-7a4c2a680c13.png)

**Comment by tamalchowdhury** [comment]
Hello Bruno, thank you very much for putting the time into posting a detailed issue. I didn't renew the domain name and that's why it's not available anymore. You can access the site by going to https://periodictableonline.netlify.app/

You may also update the readme file to update the website URL. Thanks.

**Comment by b-dantas** [comment]
> You may also update the readme file to update the website URL. Thanks.

For sure. I made a PR for that.

**Comment by diomed** [comment]
> Hello Bruno, thank you very much for putting the time into posting a detailed issue. I didn't renew the domain name and that's why it's not available anymore. You can access the site by going to https://periodictableonline.netlify.app/
> 
> You may also update the readme file to update the website URL. Thanks.

hey man. you should update link to it in your Medium article. I've found it there, but I tracked you down to github. so that's how i found working example.

**Comment by tamalchowdhury** [comment]
Hi @diomed thanks a lot. I just updated the link to Medium article. Would you be willing to check it out and lemme know if I did it right? Thanks.

**Comment by diomed** [comment]
I just checked and it's all good now. Cheers!
